---
title: "writing_functions"
author: "AnMei Chen"
date: "11/5/2021"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis" , 
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Z scores

```{r}
x_vec = rnorm(25,mean = 5, sd = 4)

(x_vec - mean(x_vec)) / sd(x_vec)

z_scores = function(x) {
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
  
}

z_scores(x = x_vec)

y_vec = rnorm(40, mean = 12, sd = .3)
z_scores(x = y_vec)
```


How great is this?
Only kinda great.
Let's try again.

```{r, error = TRUE}

z_scores(3)

z_scores(c("my","name","is", "jeff"))

mtcars
z_scores(mtcars)

```

```{r}
z_scores = function(x) {
  
  if (!is.numeric(x)) {
    stop("x needs to be numeric")
  }
  
  if (length(x) < 3) {
    stop("x should have at least 3 numbers")
  }
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
  
}
```

